name: CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2

      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.tag.outputs.tag}}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: QuizApp.apk
          asset_content_type: application/zip